# Generated by Django 3.0.6 on 2020-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название продукта')),
                ('receipt_date', models.DateField(blank=True, verbose_name='Дата поступления')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Стоимость')),
                ('unit', models.CharField(blank=True, choices=[(1, 'шт.'), (2, 'ком-т'), (3, 'уп.')], max_length=10, verbose_name='Единица измерения')),
                ('provider_name', models.CharField(blank=True, max_length=300, verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title'],
            },
        ),
    ]
