# Generated by Django 3.0.6 on 2020-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'шт.'), ('2', 'ком-т'), ('3', 'уп.')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
