# Generated by Django 3.0.6 on 2020-05-07 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200507_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 7, 23, 43, 40, 162023), verbose_name='Дата поступления'),
        ),
    ]
