# Generated by Django 3.0.6 on 2020-05-07 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200507_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата поступления'),
        ),
    ]
